name: Merge upstream branches
on:
  push:
  schedule:
    - cron:  '0 18 * * *'
  watch:
    types: [started]
jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'SQMY-dor'
          git config --global user.email 'zerohuan0@outlook.com'
          git pull --unshallow
          git remote add upstream https://github.com/7Sageer/sublink-worker.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          git fetch upstream --tags
          git push --tags
